version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    image: shortner
    container_name: shortner
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.env
    ports:
      - "8000:8000"
    networks:
      - shortner-network
    depends_on:
      - redis
  redis:
    image: redis
    container_name: shorty_redis
    volumes:
      - ./redis.conf:/redis.conf # Mount the redis.conf file
      - redis-data:/data
    ports:
      - "6380:6380"
    command: redis-server /redis.conf # Use the mounted redis.conf file
    networks:
      - shortner-network

volumes:
  redis-data:
    driver: local

networks:
  shortner-network:
