version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/production/django/Dockerfile
    image: shortner
    container_name: shortner
    volumes:
      - .:/app:z
    env_file:
      - .envs/.production/.env
    ports:
      - "8000:8000"
    networks:
      - shortner-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: shorty_redis
    env_file:
      - .envs/.production/.env
    ports:
      - "6379:6379"
    command: redis-server --requirepass shorty
    networks:
      - shortner-network

volumes:
  zookeeper-data:
    driver: local

networks:
  shortner-network:
