# Generated by Django 5.0.4 on 2024-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="shortcode",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
