# Generated by Django 5.0.4 on 2024-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_urls_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='original_url',
            field=models.CharField(max_length=2048),
        ),
    ]
